### ISSUE TITLE
Targets correctly but not attack

### ISSUE THREAD

**Issue by ghost** [Syraxius/FFXIVSyraxiusBot#1]
I have the hotkeys on the same keys as the file but it doesn't press any of the keys necessary.

**Comment by Syraxius** [comment]
Game got updated :p just fixed this. Assist should be working now, but don't use dungeon yet. Will fix dungeon by tomorrow.

**Comment by ghost** [comment]
Thanks I'll close!

**Comment by Syraxius** [comment]
Thanks @wewzer once again for the headsup!

Dungeon mode is working now!

Take note that boss mechanics are still being implemented, so most dungeons work fine during normal fights but when boss mechanics are required (e.g. need to lure certain bosses to certain places) it might not be smart enough. Still figuring out that part haha.

So far Tam Tara, Satasha and perhaps a few more dungeons that have lighter boss mechanics work perfectly.
